78 update the config chart to template out the netpol generation section of the uds package cr
defenseunicorns/uds-package-gitlab pull request #110
Opened 2024-04-17 20:38 UTC by zachariahmiller

## Description

Adds templating for internal vs external services in the netpol section of the uds package CR

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-04-17 21:24 UTC, zachariahmiller commented on charts/config/values.yaml
> +# storage:
As implemented this would be a breaking change for anyone not using our dev stack. 

Alternative would be to invert the default values to all be `internal: false`.  This would "just work", but would also not encourage people to use more locked down policies (it just works so not going to touch it). 

I can update it to go either way its just a couple of variable overrides, but wanted to discuss first. 

If kept as is, people would have to explicitly set internal: false to allow remoteGenerated: Anywhere or to use different services than what we test against in dev.

2024-04-17 22:58 UTC, Racer159 requested changes

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
>          gateway: tenant
missing selector on pages above

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
>          description: "Tempo"
should we have tempo in here if uds-core doesn't have it? I know it is "future" but is it coming soon?

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
>          description: "Migrations Storage"
I don't think migrations needs storage access?

https://repo1.dso.mil/big-bang/product/packages/gitlab/-/blob/main/chart/charts/gitlab/charts/migrations/values.yaml?ref_type=heads (no mention of minio/s3 in values)

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
^ do we know what GitLab uses the KubeAPI for and why that above thing is there?

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
>          podLabels:
```suggestion
        selector:
```

2024-04-17 22:58 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
> +        description: "Gitlab Pages Storage"
newline

2024-04-17 22:58 UTC, Racer159 commented on charts/config/values.yaml
> +# storage:
I think this is "ok" for now as long as we scream very loudly that this is a breakage and things will die - it should be obvious things are borked since GL will wait for these things to be ready before it comes up properly...

2024-04-17 23:07 UTC, mjnagel commented on charts/config/templates/uds-package.yaml
>          description: "Tempo"
Intent will be to autogen this policy once tempo is in core. It's on a branch already that way, just been shoved down too many times in priority. But would say you can leave off and expect this to be generated by core when it exists.

2024-04-17 23:22 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
>          description: "Migrations Storage"
I added things as they failed.

2024-04-17 23:23 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
>          podLabels:
Yeah I pulled in your update after I had made those changes...

2024-04-17 23:23 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
>          description: "Migrations Storage"
I can remove it and run again to double check 🤷

2024-04-17 23:32 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
>          description: "Tempo"
sure i'll delete it i had only touched it to update to selector from labels

2024-04-18 17:11 UTC, zachariahmiller commented
@Racer159 PTAL at the doc updates. I think the network things should probably move into their own file. I also updated the notes and warning s to use the alerts that look pretty 🤷 
https://github.com/orgs/community/discussions/16925

2024-04-19 00:24 UTC, Racer159 requested changes

2024-04-19 00:24 UTC, Racer159 commented on README.md
> +> **Note:** To create the registry1 flavor you will need to be logged into Iron Bank - you can find instructions on how to do this in the [Big Bang Zarf Tutorial](https://docs.zarf.dev/docs/zarf-tuto
```suggestion
> **NOTE:** To create the registry1 flavor you will need to be logged into Iron Bank - you can find instructions on how to do this in the [Big Bang Zarf Tutorial](https://docs.zarf.dev/tutorials/6-big-bang/#setup).
```
This moved, and note could match the other one.

2024-04-19 00:24 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
> +      {{- end }}
newline

2024-04-19 00:24 UTC, Racer159 commented on charts/config/templates/uds-package.yaml
> +          app: {{ .remoteSelector.app }}
It would likely be better if they could give a key value pair - the remoteSelector label may not be app

2024-04-19 00:24 UTC, Racer159 commented on docs/networking.md
> +Gitlab is configured by default to assume the internal dependencies that are used for testing (see minio, redis and postgres in the [bundle](bundle/uds-bundle.yaml)). Intentionally, permissive networ
```suggestion
GitLab is configured by default to assume the internal dependencies that are used for testing (see minio, redis and postgres in the [bundle](bundle/uds-bundle.yaml)). Intentionally, permissive network policies are not created as a default. For example, there is not a default setup of egress anywhere for pods that may need to connect to external storage. 
```

2024-04-19 00:24 UTC, Racer159 commented on docs/networking.md
> +Configure gitlab all external services and a non-default gitlab runner:
```suggestion
Configure gitlab for all external services and a non-default gitlab runner:
```

2024-04-19 00:33 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
> +          app: {{ .remoteSelector.app }}
Yeah that was an accident 🤣

2024-04-19 00:36 UTC, zachariahmiller commented on charts/config/templates/uds-package.yaml
> +      {{- end }}
Lol yeah I did helm lint and yamllint but only the yaml one picks up the new line and excludes the templates 🤣

2024-04-19 01:51 UTC, Racer159 approved these changes

2024-04-19 01:51 UTC, Racer159 commented on README.md
> +Gitlab is configured by default to assume the internal dependencies that are used for testing (see minio, redis and postgres in the [bundle](bundle/uds-bundle.yaml)).
```suggestion
GitLab is configured by default to assume the internal dependencies that are used for testing (see minio, redis and postgres in the [bundle](bundle/uds-bundle.yaml)).
```
I think its fine even though there is this :see_no_evil:

2024-04-19 01:59 UTC, zachariahmiller commented on docs/networking.md
> +> There may be a need to integrate with other in-cluster services that are not a part of the standard connectivity needed by gitlab (for example a Jira integration). As such, there is the ability to
```suggestion
> There may be a need to integrate with other in-cluster services that are not a part of the standard connectivity needed by GitLab (for example a Jira integration). As such, there is the ability to add custom rules to allow additional internal network connectivity.
```

2024-04-19 15:04 UTC, Racer159 approved these changes

2024-04-19 15:47 UTC, merged