feat: scan for vuln
defenseunicorns/uds-package-gitlab pull request #98
Opened 2024-03-30 16:57 UTC by naveensrinivasan

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-04-01 16:04 UTC, zachariahmiller requested changes

2024-04-01 16:04 UTC, zachariahmiller commented on .github/workflows/scan-vulnerability.yaml
> +      contents: read
```suggestion
      contents: read
```

2024-04-01 21:27 UTC, Racer159 requested changes
The output here is quite verbose - is it possible to dedupe some of these that are repeated?

https://github.com/defenseunicorns/uds-package-gitlab/security/code-scanning?query=pr%3A98+is%3Aopen

There also seem to be some that are titled as "medium" or "low" but labeled as "critical" or "high"

2024-04-02 15:08 UTC, naveensrinivasan commented on tasks/scanvulnerability.yaml
> +          fi
I took care of it.

2024-04-02 15:08 UTC, naveensrinivasan commented on tasks/scanvulnerability.yaml
> +  - name: grype-scan-sbom
👍

2024-04-02 15:09 UTC, naveensrinivasan commented on .github/workflows/scan-vulnerability.yaml
> +          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
👍

2024-04-02 15:09 UTC, naveensrinivasan commented on tasks.yaml
> +  - vuln-check: ./tasks/scanvulnerability.yaml
👍

2024-04-02 15:09 UTC, naveensrinivasan commented on tasks.yaml
> +      - task: vuln-check:grype-scan-sbom
👍

2024-04-02 15:09 UTC, naveensrinivasan commented on tasks/scanvulnerability.yaml
> +          done
👍

2024-04-03 17:01 UTC, naveensrinivasan commented
> The output here is quite verbose - is it possible to dedupe some of these that are repeated?
> 
> https://github.com/defenseunicorns/uds-package-gitlab/security/code-scanning?query=pr%3A98+is%3Aopen
> 
> There also seem to be some that are titled as "medium" or "low" but labeled as "critical" or "high"

1. **Image corresponding to the CVE**- all of these CVEs have which image is reporting the CVE. `registry1.dso.mil_ironbank_redhat_ubi_ubi9_9.3:1`
https://github.com/defenseunicorns/uds-package-gitlab/security/code-scanning/10337

2. **Duplicate issue** - All the zlib issues are from different containers.https://github.com/defenseunicorns/uds-package-gitlab/security/code-scanning?query=pr%3A98+is%3Aopen+zlib

3. **Critical Issue having low in the title** - The https://github.com/defenseunicorns/uds-package-gitlab/security/code-scanning/10212 is low because of the probability of exploiting the Vulnerability, and that is the reason low with Vuln being still critical.

Some help from ChatGPT for `low`
TL;DR:
- Vulnerability severity is based on potential impact, exploit complexity, mitigations, impact, user interaction, exploitation environment, patch availability, and historical context.
- Mitigating complexity, mitigations, limited impact, user interaction, and restricted exploitation environment can lower severity.
- Prompt patches and historical context also influence severity classification.
- The process ensures the effective allocation of resources to address pressing security concerns.

2024-05-29 23:18 UTC, Racer159 commented
closing this do to becoming stale (we can reopen / readdress later)

2024-05-29 23:18 UTC, closed without merging